version: "3"

services:
  backend:
    build: ./
    volumes:
      - .:/backend # maps host diretory to internal container directory
    working_dir: /app/
    command: python run.py
  frontend:
    image: node:8.9
    command: sh entrypoint.sh
    working_dir: /frontend
    volumes:
      - ./public/:/frontend
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public/build:/var/www/frontend # maps frontend build inside nginx
    depends_on:
      - backend
