[tool.poetry]
name = "shnight"
version = "0.1.0"
description = ""
authors = ["Nick Humrich <nick.humrich@gmail.com>"]

[tool.poetry.dependencies]
python = "*"
aiohttp_sse = "^2.0"
aiohttp = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
